// <auto-generated />
using System;
using System.Text.Json;
using SensorMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SensorMonitor.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    partial class TelemetryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SensorMonitor.Models.SensorTelemetry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GatewayId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonElement>("SensorData")
                        .HasColumnType("jsonb");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("sensor_telemetries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
